#!/bin/sh
JSON_STRING='window.configs = { \
  "SLIDE_API_URL":"'"${SLIDE_API_URL}"'", \
  "BASE_API_URL":"'"${BASE_API_URL}"'", \
  "AI_API_URL":"'"${AI_API_URL}"'", \
  "AUTH_API_URL":"'"${AUTH_API_URL}"'", \
  "AUTH_FRONTEND_DOMAIN":"'"${AUTH_FRONTEND_DOMAIN}"'", \
  "APP_TITLE":"'"${APP_TITLE}"'", \
  "APP_LOGO_URL":"'"${APP_LOGO_URL}"'", \
  "APP_FAVICON_URL":"'"${APP_FAVICON_URL}"'", \
  "SLIDE_IMAGE_URL":"'"${SLIDE_IMAGE_URL}"'", \
  "FRONTEND_VERSION":"'"${FRONTEND_VERSION}"'", \
  "VITE_SENTRY_DSN":"'"${VITE_SENTRY_DSN}"'", \
  "VITE_SENTRY_ENVIRONMENT":"'"${VITE_SENTRY_ENVIRONMENT}"'", \
  "VITE_WEBSOCKET_APP_KEY":"'"${VITE_WEBSOCKET_APP_KEY}"'", \
  "VITE_WEBSOCKET_HOST":"'"${VITE_WEBSOCKET_HOST}"'", \
  "VITE_WEBSOCKET_PORT":"'"${VITE_WEBSOCKET_PORT}"'", \
  "VITE_WEBSOCKET_PORT":"'"${VITE_WEBSOCKET_PORT}"'", \
  "VITE_WEBSOCKET_DEBUG":"'"${VITE_WEBSOCKET_DEBUG}"'", \
}'
sed -i "s@// CONFIGURATIONS_PLACEHOLDER@${JSON_STRING}@" /usr/share/nginx/html/index.html
exec "$@"