"""Course description Coloumn now uses TEXT instead of VARCHAR

Revision ID: 04ac99d8a7ab
Revises: 35195e81a197
Create Date: 2022-03-16 20:31:14.198726

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '04ac99d8a7ab'
down_revision = '35195e81a197'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    try:
        op.alter_column('course', 'description',
                        existing_type=mysql.VARCHAR(length=255),
                        type_=sa.Text(),
                        existing_nullable=True)
        op.add_column('task', sa.Column('can_be_solved', sa.Boolean(), nullable=True))
    except Exception as e:
        print(e)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task', 'can_be_solved')
    op.alter_column('course', 'description',
                    existing_type=sa.Text(),
                    type_=mysql.VARCHAR(length=255),
                    existing_nullable=True)
    # ### end Alembic commands ###
