"""Added info annotations

Revision ID: 1b342ac080d3
Revises: b41253647ec2
Create Date: 2021-12-06 18:11:52.835815

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "1b342ac080d3"
down_revision = "b41253647ec2"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    try:
        op.add_column("task", sa.Column("info_annotations", sa.JSON(), nullable=True))
    except Exception as e:
        print(e)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("task", "info_annotations")
    # ### end Alembic commands ###
