"""First commit

Revision ID: 7047f90165ed
Revises: 
Create Date: 2021-09-15 14:56:01.763748

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "7047f90165ed"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
