"""Added info annotations

Revision ID: b41253647ec2
Revises: d46929cd6ff2
Create Date: 2021-12-06 18:10:51.374200

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b41253647ec2'
down_revision = 'd46929cd6ff2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('info_annotations', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task', 'info_annotations')
    # ### end Alembic commands ###
