"""version 1.0

Revision ID: d46929cd6ff2
Revises: 5365d581e37c
Create Date: 2021-11-27 15:02:42.166001

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd46929cd6ff2'
down_revision = '5365d581e37c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
