"""Added user solution failed attemptsn

Revision ID: d898dc181fa0
Revises: e2bc3f87f9c3
Create Date: 2021-10-11 22:36:52.245391

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd898dc181fa0'
down_revision = 'e2bc3f87f9c3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
