"""Added user solution failed attemptsn

Revision ID: e2bc3f87f9c3
Revises: 9fa155db53d8
Create Date: 2021-10-11 22:33:37.167533

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e2bc3f87f9c3'
down_revision = '9fa155db53d8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('usersolution', 'failed_attempts',
               existing_type=mysql.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('usersolution', 'failed_attempts',
               existing_type=mysql.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
