"""TaskHint content now uses Text

Revision ID: 99eb6c5a2670
Revises: 04ac99d8a7ab
Create Date: 2022-03-23 19:12:29.897000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = "99eb6c5a2670"
down_revision = "04ac99d8a7ab"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "taskhint",
        "content",
        existing_type=mysql.VARCHAR(length=255),
        type_=sa.Text(),
        existing_nullable=True,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "taskhint",
        "content",
        existing_type=sa.Text(),
        type_=mysql.VARCHAR(length=255),
        existing_nullable=True,
    )
    # ### end Alembic commands ###
