export enum COLOR {
  FILL_COLOR = '#05D0EB33',
  STROKE_COLOR = '#05D0EB',
  BACKGROUND_COLOR = '#99999933',
  BACKGROUND_STROKE_COLOR = '#999999'
}

export enum ANNOTATION_COLOR {
  BACKGORUND_COLOR = '#D80073',
  USER_SOLUTION_COLOR = '#03d7fc',
  SOLUTION_COLOR = '#e67e22',
  MISTAKE = '#e74c3c',
  CORRECT = '#2ecc71',
  RESULT_LINE_COLOR = '#FFFF00',
  INFO_COLOR = '#FF00FF',
  FILL_OPACITY = '66'
}

export function getFillColor(color: string): string {
  return color + ANNOTATION_COLOR.FILL_OPACITY;
}
