"""Changed columns

Revision ID: 2b7444861dd9
Revises: a7a539822f9e
Create Date: 2022-12-14 20:33:54.906891

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "2b7444861dd9"
down_revision = "a7a539822f9e"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "questionnaireanswer",
        sa.Column("question_option_id", sa.Integer(), nullable=True),
    )
    op.add_column(
        "questionnaireanswer", sa.Column("selected", sa.Boolean(), nullable=True)
    )
    op.create_foreign_key(
        None,
        "questionnaireanswer",
        "questionnairequestionoption",
        ["question_option_id"],
        ["id"],
    )
    op.add_column(
        "questionnairequestionoption",
        sa.Column("with_input", sa.Boolean(), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("questionnairequestionoption", "with_input")
    op.drop_constraint(None, "questionnaireanswer", type_="foreignkey")
    op.drop_column("questionnaireanswer", "selected")
    op.drop_column("questionnaireanswer", "question_option_id")
    # ### end Alembic commands ###
