"""Changed column type

Revision ID: 4763ea1903cf
Revises: 72ca4204b3ba
Create Date: 2022-12-14 23:09:40.434717

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4763ea1903cf'
down_revision = '72ca4204b3ba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('questionnaireanswer', 'selected',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.String(length=500),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('questionnaireanswer', 'selected',
               existing_type=sa.String(length=500),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=True)
    # ### end Alembic commands ###
