"""Added questionaire option

Revision ID: 4cf7c6833aa1
Revises: 99d490a6c71d
Create Date: 2022-12-14 10:48:27.774371

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4cf7c6833aa1'
down_revision = '99d490a6c71d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
