"""Added questionnaire id

Revision ID: 5aa65b6c34ae
Revises: 4763ea1903cf
Create Date: 2022-12-14 23:56:17.030253

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "5aa65b6c34ae"
down_revision = "4763ea1903cf"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "questionnaireanswer",
        sa.Column("questionnaire_id", sa.Integer(), nullable=True),
    )
    op.create_foreign_key(
        None, "questionnaireanswer", "questionnaire", ["questionnaire_id"], ["id"]
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "questionnaireanswer", type_="foreignkey")
    op.drop_column("questionnaireanswer", "questionnaire_id")
    # ### end Alembic commands ###
