"""Version 0.0.7n

Revision ID: 7b852dfcc007
Revises: a5e49aaba65b
Create Date: 2021-11-10 18:58:16.440339

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "7b852dfcc007"
down_revision = "a5e49aaba65b"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
