"""TaskStatistic

Revision ID: 88baa0b43fe1
Revises: 7b852dfcc007
Create Date: 2021-11-10 19:19:35.500407

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "88baa0b43fe1"
down_revision = "7b852dfcc007"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
