"""task hint types are ints

Revision ID: 943cf797c278
Revises: 8e8247e7893c
Create Date: 2021-09-23 21:56:07.338197

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "943cf797c278"
down_revision = "8e8247e7893c"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
