"""Added questionaire answer

Revision ID: 9e026d3bfae6
Revises: 9f11c0e109a1
Create Date: 2022-12-14 10:27:16.953544

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9e026d3bfae6'
down_revision = '9f11c0e109a1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('questionnaireanswer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('question_id', sa.Integer(), nullable=True),
    sa.Column('answer', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['question_id'], ['questionnaireanswer.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_questionnaireanswer_id'), 'questionnaireanswer', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_questionnaireanswer_id'), table_name='questionnaireanswer')
    op.drop_table('questionnaireanswer')
    # ### end Alembic commands ###
