"""Added questionaire question

Revision ID: 9f11c0e109a1
Revises: d16b229fc039
Create Date: 2022-12-14 10:25:56.789267

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "9f11c0e109a1"
down_revision = "d16b229fc039"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "questionnairequestion",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("questionnaire_id", sa.Integer(), nullable=True),
        sa.Column("order", sa.Text(), nullable=False),
        sa.Column("question_text", sa.Text(), nullable=False),
        sa.Column("is_mandatory", sa.Boolean(), nullable=True),
        sa.Column("question_type", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["questionnaire_id"],
            ["questionnaire.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_questionnairequestion_id"),
        "questionnairequestion",
        ["id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_questionnairequestion_id"), table_name="questionnairequestion"
    )
    op.drop_table("questionnairequestion")
    # ### end Alembic commands ###
