"""0.4.2-beta

Revision ID: c35712b24b98
Revises: 5aa65b6c34ae
Create Date: 2022-12-15 01:35:25.695812

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "c35712b24b98"
down_revision = "5aa65b6c34ae"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
