"""Add superuser column

Revision ID: d5bb98bc31d4
Revises: c8ba88d4b489
Create Date: 2023-05-01 07:10:38.311706

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd5bb98bc31d4'
down_revision = 'c8ba88d4b489'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('is_superuser', sa.Boolean(), nullable=True))
    op.drop_column('user', 'middlename')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('middlename', mysql.VARCHAR(length=255), nullable=True))
    op.drop_column('user', 'is_superuser')
    # ### end Alembic commands ###
