"""Added basic task hint

Revision ID: e321bbcdb4ec
Revises: 5adfbb5e4fd6
Create Date: 2021-09-22 16:18:03.848194

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
from sqlalchemy.engine import Inspector

revision = "e321bbcdb4ec"
down_revision = "5adfbb5e4fd6"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    inspector = Inspector.from_engine(conn)
    tables = inspector.get_table_names()
    if not "taskhint" in tables:
        op.create_table(
            "taskhint",
            sa.Column("id", sa.Integer(), nullable=False),
            sa.Column("task_id", sa.Integer(), nullable=True),
            sa.Column(
                "hint_type",
                sa.Enum("TEXT", "IMAGE", "SOLUTION", name="tasktype"),
                nullable=True,
            ),
            sa.Column("content", sa.String(length=255), nullable=True),
            sa.ForeignKeyConstraint(
                ["task_id"],
                ["task.id"],
            ),
            sa.PrimaryKeyConstraint("id"),
        )
        op.create_index(op.f("ix_taskhint_id"), "taskhint", ["id"], unique=False)
    if not "hintimage" in tables:
        op.create_table(
            "hintimage",
            sa.Column("id", sa.Integer(), nullable=False),
            sa.Column("image_name", sa.String(length=255), nullable=True),
            sa.Column("task_hint_id", sa.Integer(), nullable=True),
            sa.ForeignKeyConstraint(
                ["task_hint_id"],
                ["taskhint.id"],
            ),
            sa.PrimaryKeyConstraint("id"),
        )
        op.create_index(op.f("ix_hintimage_id"), "hintimage", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_hintimage_id"), table_name="hintimage")
    op.drop_table("hintimage")
    op.drop_index(op.f("ix_taskhint_id"), table_name="taskhint")
    op.drop_table("taskhint")
    # ### end Alembic commands ###
