"""Added questionaire option fix

Revision ID: eb219c1ab270
Revises: 4cf7c6833aa1
Create Date: 2022-12-14 10:49:34.117558

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eb219c1ab270'
down_revision = '4cf7c6833aa1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('questionnairequestionoption',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=True),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('value', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['questionnairequestion.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('order')
    )
    op.create_index(op.f('ix_questionnairequestionoption_id'), 'questionnairequestionoption', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_questionnairequestionoption_id'), table_name='questionnairequestionoption')
    op.drop_table('questionnairequestionoption')
    # ### end Alembic commands ###
