"""Change task question to type TEXT

Revision ID: fb3f91aa14a3
Revises: 04ac99d8a7ab
Create Date: 2022-12-14 09:22:37.101859

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = "fb3f91aa14a3"
down_revision = "04ac99d8a7ab"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "task",
        "task_question",
        existing_type=mysql.VARCHAR(length=255),
        type_=sa.Text(),
        existing_nullable=True,
    )
    op.alter_column(
        "taskhint",
        "content",
        existing_type=mysql.VARCHAR(length=255),
        type_=sa.Text(),
        existing_nullable=True,
    )
    op.alter_column(
        "usersolution",
        "failed_attempts",
        existing_type=mysql.INTEGER(),
        nullable=False,
        existing_server_default=sa.text("(0)"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "usersolution",
        "failed_attempts",
        existing_type=mysql.INTEGER(),
        nullable=True,
        existing_server_default=sa.text("(0)"),
    )
    op.alter_column(
        "taskhint",
        "content",
        existing_type=sa.Text(),
        type_=mysql.VARCHAR(length=255),
        existing_nullable=True,
    )
    op.alter_column(
        "task",
        "task_question",
        existing_type=sa.Text(),
        type_=mysql.VARCHAR(length=255),
        existing_nullable=True,
    )
    # ### end Alembic commands ###
